GO
USE [SEDPLAN];
GO

CREATE PROCEDURE dbo.stp_ShowSubAssemblyList
		  @ProjectNo NVARCHAR(100),
		  @FabricationList NVARCHAR(MAX)
AS
BEGIN

	--DECLARE @ProjectNo VARCHAR(15)='S32A1305700';
	--DECLARE @FabricationList VARCHAR(200)='SAB-BCV01-B03 02';

	SELECT	* INTO #TMP_BOM_PLAN 
	FROM	BOM_Plan BP
	WHERE	BP.Project_No=@ProjectNo AND BP.Plan_Name IN (@FabricationList)
		AND	BP.Revision=(SELECT MAX(Revision) FROM BOM_Plan BP2 WHERE BP2.Plan_Name=BP.Plan_Name AND BP2.Project_No=BP.Project_No)

	SELECT SI.SA_DESCRIPTION,ALLBP.SA_ID,L_VAL,LS_VAL,A_VAL,TB_VAL,H_VAL,EW_VAL,LR_VAL,SUM(QUANTITY)AS QUANTITY,COLOR 
	FROM(
		SELECT 
		BP.SA_ID,
		BP_L.VAR_VALUE AS L_VAL,
		BP_LS.VAR_VALUE AS LS_VAL,
		BP_A.VAR_VALUE AS A_VAL,
		BP_TB.VAR_VALUE AS TB_VAL, 
		BP_H.VAR_VALUE AS H_VAL,
		BP_EW.VAR_Value AS EW_VAL,
		BP_LR.VAR_VALUE AS LR_VAL,
		BP.QUANTITY,
		BP.COLOR
		FROM #TMP_BOM_PLAN BP
		LEFT JOIN #TMP_BOM_PLAN BP_L ON BP.SAUID=BP_L.SAUID AND BP.Revision=BP_L.Revision AND BP_L.VAR_TYPE='L'
		LEFT JOIN #TMP_BOM_PLAN BP_LS ON BP.SAUID=BP_LS.SAUID AND BP.Revision=BP_LS.Revision AND BP_LS.VAR_TYPE='LS'
		LEFT JOIN #TMP_BOM_PLAN BP_A ON BP.SAUID=BP_A.SAUID AND BP.Revision=BP_A.Revision AND BP_A.VAR_TYPE='A¡ã'
		LEFT JOIN #TMP_BOM_PLAN BP_H ON BP.SAUID=BP_H.SAUID AND BP.Revision=BP_H.Revision AND BP_H.VAR_TYPE='H'
		LEFT JOIN #TMP_BOM_PLAN BP_TB ON BP.SAUID=BP_TB.SAUID AND BP.Revision=BP_TB.Revision AND BP_TB.VAR_TYPE='TB'
		LEFT JOIN #TMP_BOM_PLAN BP_EW ON BP.SAUID=BP_EW.SAUID AND BP.Revision=BP_EW.Revision AND BP_EW.VAR_TYPE='EW'
		LEFT JOIN #TMP_BOM_PLAN BP_LR ON BP.SAUID=BP_LR.SAUID AND BP.Revision=BP_LR.Revision AND BP_LR.VAR_TYPE='LR'
		WHERE BP.Project_No=@ProjectNo AND BP.Plan_Name IN (@FabricationList) AND BP.ISMAIN=1
		AND BP.Revision=(SELECT MAX(Revision) FROM BOM_Plan BP2 WHERE BP2.Plan_Name=BP.Plan_Name AND BP2.Project_No=BP.Project_No)
	) AS ALLBP
	LEFT JOIN SA_INFO SI 
		ON ALLBP.SA_ID=SI.SA_ID
		AND SI.Revision=(SELECT MAX(Revision) FROM SA_INFO SI2 WHERE SI2.SA_ID=SI.SA_ID)
	GROUP BY SI.SA_DESCRIPTION,ALLBP.SA_ID,L_VAL,LS_VAL,A_VAL,TB_VAL,H_VAL,EW_VAL,LR_VAL,COLOR;

END

--DECLARE @ProjectNo VARCHAR(15)='S32A1305700';
--DECLARE @FabricationList VARCHAR(200)='SAB-BCV01-B03 02';
--EXEC stp_ShowSubAssemblyList @ProjectNo, @FabricationList;