GO
USE [SEDPLAN];
GO

ALTER PROCEDURE dbo.stp_ImportDDTData
		  @SAID NVARCHAR(100),
		  @PARTSNAME NVARCHAR(100),
		  @PARATYPE NVARCHAR(100),
		  @PARAVALUE NVARCHAR(100),
		  @DDID NVARCHAR(100),
		  @Revision NVARCHAR(100),
		  @CRTIME NVARCHAR(100)
AS
BEGIN

	BEGIN TRANSACTION;
	BEGIN TRY
		DECLARE @SA_ID NVARCHAR(50) = @SAID;
		DECLARE @Parts_Name NVARCHAR(100) = @PARTSNAME;
		DECLARE @Para_Type NVARCHAR(5) = @PARATYPE;
		DECLARE @Para_Value NVARCHAR(50) = @PARAVALUE;
		DECLARE @DD_ID NVARCHAR(50) = @DDID;
		DECLARE @NewRevision INT = CAST(@Revision AS INT);
		DECLARE @Created_Time Datetime = CAST(@CRTIME AS datetime);

		INSERT INTO DD_TYPES(SA_ID,Parts_Name,Para_Type,Para_Value,DD_ID,Revision,Created_Time)
		VALUES(@SA_ID,@Parts_Name,@Para_Type,@Para_Value,@DD_ID,@NewRevision,@Created_Time);
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT>0
			ROLLBACK TRANSACTION;
		THROW
	END CATCH;

	IF @@TRANCOUNT>0
		COMMIT TRANSACTION;
END