GO
USE [SEDPLAN];
GO

ALTER PROCEDURE dbo.stp_ImportDDTData
		  @SAID NVARCHAR(100),
		  @PARTSNAME NVARCHAR(100),
		  @PARATYPE NVARCHAR(100),
		  @PARAVALUE NVARCHAR(100),
		  @DDID NVARCHAR(100),
		  @Revision NVARCHAR(100),
		  @CRTIME NVARCHAR(100)
AS
BEGIN

	BEGIN TRANSACTION;
	BEGIN TRY
		DECLARE @SA_ID NVARCHAR(50) = @SAID;
		DECLARE @Parts_Name NVARCHAR(100) = @PARTSNAME;
		DECLARE @Para_Type NVARCHAR(5) = @PARATYPE;
		DECLARE @Para_Value NVARCHAR(50) = @PARAVALUE;
		DECLARE @DD_ID NVARCHAR(50) = @DDID;
		DECLARE @NewRevision INT = CAST(@Revision AS INT);
		DECLARE @Created_Time Datetime = CAST(@CRTIME AS datetime);

		DECLARE @ERRMSG VARCHAR(max);
		IF DBO.FUN_DDT_DDID_EXISTS(@DD_ID)=0
		BEGIN
			SET @ERRMSG = 'Cannot find Detail ID. Detail ID:' + @DD_ID + '.'  + CHAR(13) + CHAR(10);;
			SET @ERRMSG = @ERRMSG + '@/' + @SA_ID + '/' + @Parts_Name + '/' + @Para_Type + '/' + @Para_Value + CHAR(13) + CHAR(10);
			THROW 60001,@ERRMSG,1
		END

		INSERT INTO DD_TYPES(SA_ID,Parts_Name,Para_Type,Para_Value,DD_ID,Revision,Created_Time)
		VALUES(@SA_ID,@Parts_Name,@Para_Type,@Para_Value,@DD_ID,@NewRevision,@Created_Time);
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT>0
			ROLLBACK TRANSACTION;
		THROW
	END CATCH;

	IF @@TRANCOUNT>0
		COMMIT TRANSACTION;
END