GO
USE [SEDPLAN];
GO

ALTER PROCEDURE dbo.stp_ImportBPData2
		  @PlanName NVARCHAR(100),
		  @SAID NVARCHAR(100),
		  @Quantity NVARCHAR(100),
		  @PARAS NVARCHAR(MAX),
		  @Revision NVARCHAR(100),
		  @CRTIME NVARCHAR(100)
AS
BEGIN
	BEGIN TRANSACTION;
	BEGIN TRY
		DECLARE @Plan_Name NVARCHAR(100) = @PlanName;
		DECLARE @SA_ID NVARCHAR(50) = @SAID;
		DECLARE @VAR_Type NVARCHAR(5);
		DECLARE @VAR_Value NVARCHAR(50);
		DECLARE @Qty INT = CAST(@Quantity AS INT);
		DECLARE @IsMain BIT = 0;
		DECLARE @NewRevision INT = CAST(@Revision AS INT);
		DECLARE @Created_Time Datetime = CAST(@CRTIME AS datetime);

		DECLARE @MARK BIT = 0;

		DECLARE @PARA_NAME NVARCHAR(5);
		DECLARE @PARA NVARCHAR(50);

		SELECT * INTO #PARANAMES
		FROM DBO.RPT_GETPARAMETERS('L,LS,A,TB,H');

		SELECT * INTO #PARAS
		FROM DBO.RPT_GETPARAMETERS(@PARAS);

		DECLARE PARANAME_CURSOR CURSOR FOR SELECT PAR FROM #PARANAMES;
		OPEN PARANAME_CURSOR;

		DECLARE PARA_CURSOR CURSOR FOR SELECT PAR FROM #PARAS;
		OPEN PARA_CURSOR
		
		FETCH NEXT FROM PARANAME_CURSOR INTO @PARA_NAME;
		FETCH NEXT FROM PARA_CURSOR INTO @PARA;
		WHILE @@FETCH_STATUS = 0
		BEGIN
			IF @PARA != ''
			BEGIN
				SET @VAR_Type = @PARA_NAME;
				SET @VAR_Value = @PARA;
				IF @MARK = 0
				BEGIN
					SET @MARK = 1;
					SET @IsMain = 1;
				END
				ELSE 
				BEGIN
					SET @IsMain = 0;
				END

				INSERT INTO BOM_Plan(Plan_Name,SA_ID,VAR_Type,VAR_Value,Quantity,IsMain,Revision,Created_Time)
				VALUES(@Plan_Name,@SA_ID,@VAR_Type,@VAR_Value,@Qty,@IsMain,@NewRevision,@Created_Time);
			END

			FETCH NEXT FROM PARANAME_CURSOR INTO @PARA_NAME;
			FETCH NEXT FROM PARA_CURSOR INTO @PARA;
			
		END

		IF @MARK = 0
		BEGIN
			SET @IsMain = 1;
			SET @VAR_Type = 'F';
			SET @VAR_Value = '-';
			INSERT INTO BOM_Plan(Plan_Name,SA_ID,VAR_Type,VAR_Value,Quantity,IsMain,Revision,Created_Time)
			VALUES(@Plan_Name,@SA_ID,@VAR_Type,@VAR_Value,@Qty,@IsMain,@NewRevision,@Created_Time);
		END
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT>0
			ROLLBACK TRANSACTION;
		THROW
	END CATCH;

	IF @@TRANCOUNT>0
		COMMIT TRANSACTION;
END