GO
USE [SEDPLAN];
GO

ALTER PROCEDURE dbo.stp_ImportSAIFData
		  @SAID NVARCHAR(100),
		  @Dscp NVARCHAR(100),
		  @Revision NVARCHAR(100),
		  @CRTIME NVARCHAR(100)
AS
BEGIN

	BEGIN TRANSACTION;
	BEGIN TRY

		DECLARE @NewRevision INT = CAST(@Revision AS INT);
		DECLARE @Created_Time Datetime = CAST(@CRTIME AS datetime);

		INSERT INTO SA_INFO(SA_ID,SA_DESCRIPTION,Revision,Created_Time)
		VALUES(@SAID,@Dscp,@NewRevision,@Created_Time);

	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT>0
			ROLLBACK TRANSACTION;
		THROW
	END CATCH;

	IF @@TRANCOUNT>0
		COMMIT TRANSACTION;
END