GO
USE [SEDPLAN];
GO

ALTER FUNCTION DBO.FUN_BP_VAR_EXISTS(@SA_ID NVARCHAR(50),@VAR_TYPE NVARCHAR(5),@VAR_Value NVARCHAR(50))
RETURNS BIT
AS
BEGIN

	DECLARE @ISEXISTS BIT;

	IF EXISTS
	(
		SELECT SA_ID,VAR_Type,VAR_Value,VAR_Weight
		FROM SA_Variable_Map SVM
		WHERE SVM.SA_ID = @SA_ID
		AND SVM.VAR_Type = @VAR_TYPE
		AND SVM.VAR_Value = @VAR_Value
		AND SVM.Revision=(SELECT MAX(Revision) FROM SA_Variable_Map SVM2 WHERE SVM2.SA_ID=@SA_ID)
	) OR @VAR_TYPE = 'F'
		SET @ISEXISTS=1;
	ELSE
		SET @ISEXISTS=0;

	RETURN @ISEXISTS;

END

--drop FUNCTION DBO.FUN_VAR_EXISTS;