GO
USE [SEDPLAN];
GO

ALTER FUNCTION DBO.FUN_SAIDVAR_EXISTS(@SA_ID NVARCHAR(50),@VAR_TYPE NVARCHAR(5),@IsVariable BIT)
RETURNS BIT
AS
BEGIN

	DECLARE @ISEXISTS BIT;

	IF EXISTS
	(
		SELECT SA_ID,VAR_Type
		FROM SA_Variable_Map SVM
		WHERE SVM.SA_ID = @SA_ID
		AND((@IsVariable=1
			AND SVM.VAR_Type = @VAR_TYPE
			AND SVM.Revision=(SELECT MAX(Revision) FROM SA_Variable_Map SVM2 WHERE SVM2.SA_ID=@SA_ID)
			) OR @IsVariable=0)
	)
		SET @ISEXISTS=1;
	ELSE
		SET @ISEXISTS=0;



	RETURN @ISEXISTS;

END