GO
USE [SEDPLAN];
GO

ALTER FUNCTION DBO.FUN_BP_VAR_EXISTS(
@SA_ID NVARCHAR(50),
@VAR_TYPE NVARCHAR(5),
@VAR_Value NVARCHAR(50)
)
RETURNS BIT
AS
BEGIN

	DECLARE @ISEXISTS BIT;
	DECLARE @ERRMSG NVARCHAR(200);

	IF @VAR_TYPE='TB' OR @VAR_TYPE='H'
	BEGIN
		IF EXISTS
		(
			SELECT DD_ID
			FROM DD_TYPES DDT,SA_Component SC
			WHERE SC.SA_ID=@SA_ID AND SC.Para_Type=@VAR_TYPE
			AND SC.Revision=(SELECT MAX(Revision) FROM SA_Component SC2 WHERE SC2.SA_ID=@SA_ID)
			AND SC.Parts_Name=DDT.Parts_Name AND DDT.SA_ID = SC.SA_ID
			AND DDT.Para_Type=@VAR_TYPE AND DDT.Para_Value=@VAR_Value
			AND DDT.Revision=(SELECT MAX(Revision) FROM DD_TYPES DDT2 WHERE DDT2.SA_ID=@SA_ID)
		)
			SET @ISEXISTS=1;
		ELSE
		BEGIN
			SET @ISEXISTS=0;
			--SET @ERRMSG = 'The parameters are not complete. Please Check. SA ID:'+@SA_ID + ', VAR TYPE:' + @VAR_TYPE + ', VAR VALUE:' + @VAR_Value + char(13)+char(10);
			--THROW 60001,@ERRMSG,1
		END
	END
	ELSE
	BEGIN
		IF EXISTS
		(
			SELECT SA_ID
			FROM SA_Component SC
			WHERE SC.SA_ID=@SA_ID AND SC.VAR_Type=@VAR_TYPE AND SC.IsVariable=1
		)
			SET @ISEXISTS=1;
		ELSE
			SET @ISEXISTS=0;
	END

	RETURN @ISEXISTS;

END

