GO
USE [SEDPLAN];
GO

ALTER FUNCTION DBO.FUN_SC_VAR_EXISTS(@Specification NVARCHAR(100),@VAR_TYPE NVARCHAR(5),@IsVariable BIT,@Para_Type NVARCHAR(5))
RETURNS BIT
AS
BEGIN

	DECLARE @ISEXISTS BIT;

	IF EXISTS
	(
		SELECT DD_ID
		FROM DD_Variable_Map DDV
		WHERE DDV.DD_ID = @Specification
			AND (@IsVariable=1 OR @VAR_TYPE='F')
			AND @Para_Type =''
			AND DDV.VAR_Type = @VAR_TYPE
			AND DDV.Revision=(SELECT MAX(Revision) FROM DD_Variable_Map DDV2 WHERE DDV2.DD_ID=@Specification)
			
	) OR (@IsVariable = 0 AND @VAR_TYPE!='F' ) OR @Para_Type != ''
		SET @ISEXISTS = 1;
	ELSE
		SET @ISEXISTS=0;

	RETURN @ISEXISTS;

END